In [1]:
#sort,Search,counting functions

In [2]:
import numpy as np

In [5]:
arr=np.array([3,4,5,6,66,77,433])

In [6]:
arr

array([  3,   4,   5,   6,  66,  77, 433])

In [7]:
np.sort(arr)

array([  3,   4,   5,   6,  66,  77, 433])

In [8]:
np.searchsorted(arr,34)

4

In [9]:
arr1=np.array([0,232,3,4,4])

In [10]:
np.count_nonzero(arr1)

4

In [11]:
np.where(arr>6)

(array([4, 5, 6], dtype=int64),)

In [12]:
np.extract(arr>6,arr)

array([ 66,  77, 433])

In [13]:
arr

array([  3,   4,   5,   6,  66,  77, 433])

In [14]:
arr.byteswap()

array([   50331648,    67108864,    83886080,   100663296,  1107296256,
        1291845632, -1325334528])

In [15]:
arr

array([  3,   4,   5,   6,  66,  77, 433])

In [17]:
a=np.copy(arr) #deep copy

In [25]:
b=arr.view()

In [29]:
b[1]=67

In [30]:
b

array([ 67,  67,   5,   6,  66,  77, 433])

In [32]:
arr

array([ 67,  67,   5,   6,  66,  77, 433])

In [33]:
#Numpy -Matrix Library

In [34]:
import numpy.matlib as nm

In [36]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [38]:
nm.ones(30)

matrix([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [40]:
# Numpy - Linear Algebra

In [47]:
arr1=np.random.randint([[5,3],[2,4]])

In [48]:
arr2=np.random.randint([[5,3],[2,4]])

In [49]:
np.dot(arr1,arr2)

array([[11,  9],
       [ 3,  1]])

In [50]:
arr1@arr2

array([[11,  9],
       [ 3,  1]])