In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [3]:
ar=np.array([1,2,3,4])

In [4]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a=[2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
b=np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [13]:
a=np.array(l)

In [14]:
c=a

In [15]:
c

array([1, 2, 3, 4])

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c[0]=22

In [18]:
c

array([22,  2,  3,  4])

In [19]:
a

array([22,  2,  3,  4])

In [20]:
d=np.copy(a)

In [21]:
d

array([22,  2,  3,  4])

In [22]:
a

array([22,  2,  3,  4])

In [23]:
a[1]=400

In [24]:
a

array([ 22, 400,   3,   4])

In [25]:
b

matrix([[1, 2, 3, 4]])

In [35]:
d

array([22,  2,  3,  4])

In [26]:
np.fromfunction(lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [28]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
iterable=(i*i for i in range(5))

In [30]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [31]:
np.fromstring('232 232',sep=' ')

array([232., 232.])

In [32]:
np.fromstring('4,5',sep=',')

array([4., 5.])

In [33]:
#Numpy -Data types

In [34]:
l=[2,3,5,6]

In [35]:
ar=np.array(l)

In [36]:
ar

array([2, 3, 5, 6])

In [37]:
ar.ndim

1

In [38]:
ar2=np.array([[1,2,3,4,5], [2,3,4,5]])

C:\Users\kmrsh\AppData\Local\Temp\ipykernel_26068\255660076.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar2=np.array([[1,2,3,4,5], [2,3,4,5]])


In [39]:
ar2

array([list([1, 2, 3, 4, 5]), list([2, 3, 4, 5])], dtype=object)

In [40]:
ar2.ndim

1

In [41]:
ar2.size

2

In [42]:
ar.shape

(4,)

In [43]:
ar.dtype

dtype('int32')

In [44]:
ar22=np.array([(1.2,4,55),(22,33,44)])

In [45]:
ar22

array([[ 1.2,  4. , 55. ],
       [22. , 33. , 44. ]])

In [46]:
ar22.dtype

dtype('float64')

In [47]:
list(range(4))

[0, 1, 2, 3]

In [48]:
np.arange(2.3,5.6,.2)

array([2.3, 2.5, 2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7,
       4.9, 5.1, 5.3, 5.5])

In [49]:
list(np.arange(2,3,.5))

[2.0, 2.5]

In [50]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [51]:
np.zeros(4)

array([0., 0., 0., 0.])

In [52]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
arr=np.zeros((5,4,2))

In [54]:
arr.ndim

3

In [55]:
on=np.ones((2,3,2))

In [56]:
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [57]:
on+3

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [58]:
on*2

array([[[2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.]]])

In [59]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [62]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [63]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [64]:
np.empty((2,5))

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [68]:
np.ones(4)

array([1., 1., 1., 1.])

In [69]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [72]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [78]:
arr=np.random.randn(3,4) #here mean is 0 and std deviation is 1

In [79]:
import pandas as pd

In [80]:
pd.DataFrame(arr)

0         1         2         3
0 -0.804896  0.999279  0.172494 -1.344298
1  0.090429 -2.035682 -1.121183 -0.237938
2 -2.530780 -0.110535  0.518545 -0.611866

In [81]:
np.random.rand(3,4)

array([[0.58078394, 0.15809942, 0.98007272, 0.69105239],
       [0.41933996, 0.49422056, 0.61271931, 0.19428849],
       [0.60112245, 0.16700141, 0.07134398, 0.45501546]])

In [84]:
pd.DataFrame(np.random.randint(1,110,(3,4)))

0    1   2   3
0   70  104  35  23
1  109   23  86  74
2   31   73  14  33

In [85]:
arr=np.random.rand(3,4)

In [89]:
arr1=arr.reshape(6,-1)

In [90]:
arr1

array([[0.1542624 , 0.95327309],
       [0.74257698, 0.2160021 ],
       [0.19817649, 0.54745304],
       [0.93104881, 0.54365171],
       [0.48401207, 0.47282616],
       [0.87516624, 0.55675602]])

In [92]:
arr1[1][1]

0.21600209588529962

In [94]:
arr1[2:5][1]

array([0.93104881, 0.54365171])

In [95]:
arr1[2:4,1]

array([0.54745304, 0.54365171])

In [97]:
arr=np.random.randint(1,100,(2,4))

In [98]:
arr>40

array([[False, False,  True,  True],
       [False,  True,  True, False]])

In [99]:
arr[arr>40]

array([94, 91, 80, 80])

In [100]:
arr

array([[ 5, 27, 94, 91],
       [17, 80, 80, 31]])

In [102]:
arr[:,2:4]

array([[94, 91],
       [80, 31]])

In [103]:
arr[0]

array([ 5, 27, 94, 91])

In [104]:
arr[0][0]=5000

In [107]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [108]:
arr1

array([[1, 2, 1],
       [1, 2, 2],
       [1, 2, 2]])

In [109]:
arr2

array([[2, 1, 2],
       [2, 1, 1],
       [2, 1, 1]])

In [110]:
arr1+arr2

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [111]:
arr1-arr2

array([[-1,  1, -1],
       [-1,  1,  1],
       [-1,  1,  1]])

In [112]:
arr1/arr2

array([[0.5, 2. , 0.5],
       [0.5, 2. , 2. ],
       [0.5, 2. , 2. ]])

In [113]:
arr1*arr2

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [114]:
arr1@arr2

array([[ 8,  4,  5],
       [10,  5,  6],
       [10,  5,  6]])

In [115]:
arr1/0

C:\Users\kmrsh\AppData\Local\Temp\ipykernel_26068\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [116]:
arr1+100

array([[101, 102, 101],
       [101, 102, 102],
       [101, 102, 102]])

In [117]:
arr1**2

array([[1, 4, 1],
       [1, 4, 4],
       [1, 4, 4]], dtype=int32)

In [118]:
#Numpy -Broadcasting

In [119]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
row=np.array([1,2,3,4])

In [123]:
arr+row

array([[5001,   29,   97,   95],
       [  18,   82,   83,   35]])

In [125]:
row.ndim

1

In [126]:
row.shape

(4,)

In [127]:
row.T

array([1, 2, 3, 4])

In [129]:
col=np.array([[1,2,3,4]])

In [130]:
np.random.randint(1,4,(2,4))

array([[1, 1, 2, 1],
       [2, 2, 1, 2]])

In [132]:
np.sqrt(arr)

array([[70.71067812,  5.19615242,  9.69535971,  9.53939201],
       [ 4.12310563,  8.94427191,  8.94427191,  5.56776436]])

In [135]:
np.log10(arr)

array([[3.69897   , 1.43136376, 1.97312785, 1.95904139],
       [1.23044892, 1.90308999, 1.90308999, 1.49136169]])