In [1]:
#Numpy - Array Manipulation

In [2]:
import numpy as np

In [4]:
arr=np.random.randint(1,10,(3,4))

In [5]:
arr

array([[8, 5, 5, 5],
       [1, 1, 9, 1],
       [8, 1, 6, 9]])

In [6]:
arr.reshape(6,2)

array([[8, 5],
       [5, 5],
       [1, 1],
       [9, 1],
       [8, 1],
       [6, 9]])

In [9]:
arr.reshape(2,-227)

array([[8, 5, 5, 5, 1, 1],
       [9, 1, 8, 1, 6, 9]])

In [10]:
arr.T

array([[8, 1, 8],
       [5, 1, 1],
       [5, 9, 6],
       [5, 1, 9]])

In [11]:
arr.flatten()

array([8, 5, 5, 5, 1, 1, 9, 1, 8, 1, 6, 9])

In [12]:
arr1=np.array([1,2,3,4])

In [13]:
arr1.ndim

1

In [15]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [16]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4]])

In [20]:
np.reshape(arr1,(1,4))

array([[1, 2, 3, 4]])

In [22]:
np.squeeze(arr)

array([[8, 5, 5, 5],
       [1, 1, 9, 1],
       [8, 1, 6, 9]])

In [23]:
data=np.array([[1],[2],[3]])

In [24]:
data

array([[1],
       [2],
       [3]])

In [25]:
np.squeeze(data)

array([1, 2, 3])

In [27]:
arr1

array([1, 2, 3, 4])

In [28]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [33]:
np.roll(arr1,2)

array([3, 4, 1, 2])

In [34]:
arr1

array([1, 2, 3, 4])

In [35]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [36]:
#Numpy -Binary Operations.

In [37]:
arr1=np.random.randint(1,10,(3,4))

In [38]:
arr2=np.random.randint(1,10,(3,4))

In [39]:
arr1+arr2

array([[ 9, 16,  6, 14],
       [10,  9, 15, 10],
       [11, 14, 10,  9]])

In [40]:
arr1*arr2

array([[14, 63,  8, 45],
       [24,  8, 54,  9],
       [18, 45,  9, 20]])

In [41]:
arr1/arr2

array([[3.5       , 0.77777778, 2.        , 1.8       ],
       [0.66666667, 0.125     , 0.66666667, 9.        ],
       [0.22222222, 1.8       , 9.        , 1.25      ]])

In [42]:
arr1-arr2

array([[ 5, -2,  2,  4],
       [-2, -7, -3,  8],
       [-7,  4,  8,  1]])

In [43]:
arr1%arr2

array([[1, 7, 0, 4],
       [4, 1, 6, 0],
       [2, 4, 0, 1]], dtype=int32)

In [44]:
arr1**arr2

array([[      49, 40353607,       16,    59049],
       [    4096,        1, 10077696,        9],
       [     512,    59049,        9,      625]], dtype=int32)

In [46]:
arr1&arr2

array([[2, 1, 0, 1],
       [4, 0, 0, 1],
       [0, 1, 1, 4]], dtype=int32)

In [48]:
~arr1

array([[ -8,  -8,  -5, -10],
       [ -5,  -2,  -7, -10],
       [ -3, -10, -10,  -6]], dtype=int32)

In [49]:
arr1|arr2

array([[ 7, 15,  6, 13],
       [ 6,  9, 15,  9],
       [11, 13,  9,  5]], dtype=int32)

In [50]:
arr1>arr2

array([[ True, False,  True,  True],
       [False, False, False,  True],
       [False,  True,  True,  True]])

In [53]:
arr=np.array(['Kumar','shivam'])

In [54]:
np.char.upper(arr)

array(['KUMAR', 'SHIVAM'], dtype='<U6')

In [55]:
np.char.title(arr)

array(['Kumar', 'Shivam'], dtype='<U6')

In [56]:
np.char.capitalize(arr)

array(['Kumar', 'Shivam'], dtype='<U6')

In [57]:
#Numpy -Mathematical Functions

In [59]:
arr1

array([[7, 7, 4, 9],
       [4, 1, 6, 9],
       [2, 9, 9, 5]])

In [60]:
np.sin(arr1)

array([[ 0.6569866 ,  0.6569866 , -0.7568025 ,  0.41211849],
       [-0.7568025 ,  0.84147098, -0.2794155 ,  0.41211849],
       [ 0.90929743,  0.41211849,  0.41211849, -0.95892427]])

In [61]:
np.cos(arr1)

array([[ 0.75390225,  0.75390225, -0.65364362, -0.91113026],
       [-0.65364362,  0.54030231,  0.96017029, -0.91113026],
       [-0.41614684, -0.91113026, -0.91113026,  0.28366219]])

In [62]:
np.tanh(arr1)

array([[0.99999834, 0.99999834, 0.9993293 , 0.99999997],
       [0.9993293 , 0.76159416, 0.99998771, 0.99999997],
       [0.96402758, 0.99999997, 0.99999997, 0.9999092 ]])

In [63]:
np.log10(arr1)

array([[0.84509804, 0.84509804, 0.60205999, 0.95424251],
       [0.60205999, 0.        , 0.77815125, 0.95424251],
       [0.30103   , 0.95424251, 0.95424251, 0.69897   ]])

In [64]:
np.exp(arr1)

array([[1.09663316e+03, 1.09663316e+03, 5.45981500e+01, 8.10308393e+03],
       [5.45981500e+01, 2.71828183e+00, 4.03428793e+02, 8.10308393e+03],
       [7.38905610e+00, 8.10308393e+03, 8.10308393e+03, 1.48413159e+02]])

In [65]:
np.sqrt(arr1)

array([[2.64575131, 2.64575131, 2.        , 3.        ],
       [2.        , 1.        , 2.44948974, 3.        ],
       [1.41421356, 3.        , 3.        , 2.23606798]])

In [67]:
np.power(arr1,2)

array([[49, 49, 16, 81],
       [16,  1, 36, 81],
       [ 4, 81, 81, 25]], dtype=int32)

In [68]:
np.mean(arr1)

6.0

In [69]:
np.median(arr1)

6.5

In [72]:
np.std(arr1)

2.70801280154532

In [73]:
np.min(arr1)

1

In [74]:
np.max(arr1)

9